pipeline {

    agent any


    parameters {

        choice(
            name: 'ACTION',
            choices: [
                'PLAN',
                'APPLY',
                'DESTROY'
            ],
            description: 'Select Terraform Action'
        )


        string(
            name: 'TFVARS_FILE',
            defaultValue: 'terraform.tfvars',
            description: 'Enter Terraform variables file name (.tfvars)'
        )

    }



    options {

        disableConcurrentBuilds()

        timestamps()

    }



    environment {

        TF_IN_AUTOMATION = "true"

        AWS_DEFAULT_REGION = "ap-south-1"

    }



    stages {


        stage('Checkout Code') {

            steps {

                checkout scm

            }

        }





        stage('Environment Check') {

            steps {


                dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {


                    sh '''

                    echo "=============================="

                    echo "Terraform Version"

                    terraform version


                    echo "=============================="

                    echo "AWS Identity"

                    aws sts get-caller-identity


                    echo "=============================="

                    echo "Terraform Files"

                    ls -ltr *.tf

                    ls -ltr *.tfvars


                    echo "=============================="

                    '''

                }

            }

        }







        stage('Set Terraform State') {

            steps {

                script {


                    def stateName = params.TFVARS_FILE
                                      .replace('.tfvars','')


                    env.TF_STATE_KEY = "${stateName}/terraform.tfstate"


                    echo "Using Terraform State:"
                    echo "${TF_STATE_KEY}"


                }

            }

        }








        stage('Validate TFVARS File') {


            steps {


                dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {


                    sh """

                    if [ ! -f ${params.TFVARS_FILE} ]; then

                        echo "${params.TFVARS_FILE} not found"

                        exit 1

                    fi


                    echo "Using:"
                    echo "${params.TFVARS_FILE}"


                    """

                }

            }

        }








        stage('Terraform Init') {


            steps {


                dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {


                    sh """

                    terraform init \
                    -reconfigure \
                    -backend-config="key=${TF_STATE_KEY}"


                    """

                }

            }

        }








        stage('Terraform Validate') {


            steps {


                dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {


                    sh '''

                    terraform validate

                    '''

                }

            }

        }








        stage('Terraform Plan') {


            when {


                expression {


                    params.ACTION == 'PLAN' ||
                    params.ACTION == 'APPLY'


                }

            }



            steps {


                dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {


                    sh """

                    terraform plan \
                    -var-file=${params.TFVARS_FILE} \
                    -lock-timeout=5m \
                    -out=tfplan


                    """

                }

            }

        }









        stage('Terraform Apply') {


            when {


                expression {


                    params.ACTION == 'APPLY'


                }

            }



            steps {


                dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {


                    sh """

                    terraform apply \
                    -auto-approve \
                    tfplan


                    """

                }

            }

        }








        stage('Terraform Destroy') {


            when {


                expression {


                    params.ACTION == 'DESTROY'


                }

            }



            steps {


                dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {


                    sh """

                    terraform destroy \
                    -auto-approve \
                    -var-file=${params.TFVARS_FILE} \
                    -lock-timeout=5m


                    """

                }

            }

        }


    }




    post {


        always {

            echo "Terraform Pipeline Completed"

        }


        success {

            echo "Terraform Deployment Successful"

        }


        failure {

            echo "Terraform Deployment Failed"

        }


    }


}
