pipeline {

    agent any


    parameters {

        choice(
            name: 'ACTION',
            choices: [
                'PLAN',
                'APPLY',
                'DESTROY'
            ],
            description: 'Select Terraform Action'
        )


        string(
            name: 'TFVARS_FILE',
            defaultValue: 'terraform.tfvars',
            description: 'Terraform variable file name'
        )

    }



    options {

        disableConcurrentBuilds()

        timestamps()

    }



    environment {

        TF_IN_AUTOMATION = "true"

        AWS_DEFAULT_REGION = "ap-south-1"

    }



    stages {


        stage('Checkout Code') {

            steps {

                checkout scm

            }

        }



        stage('Environment Check') {

            steps {

                dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {

                    sh '''

                    echo "Terraform Version"

                    terraform version


                    echo "AWS Account"

                    aws sts get-caller-identity


                    echo "Terraform Files"

                    ls -ltr *.tfvars


                    '''

                }

            }

        }





        stage('Set Terraform State') {

            steps {

                script {


                    def envName = params.TFVARS_FILE
                                    .replace('.tfvars','')


                    env.TF_STATE_KEY = "${envName}/terraform.tfstate"


                    echo "Terraform State:"
                    echo "${env.TF_STATE_KEY}"


                }

            }

        }







        stage('Terraform Init') {

            steps {

                dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {


                    sh """

                    terraform init \
                    -backend-config="key=${TF_STATE_KEY}"


                    """

                }

            }

        }







        stage('Terraform Validate') {


            steps {


                dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {


                    sh """

                    terraform validate

                    """

                }

            }

        }








        stage('Terraform Plan') {


            when {


                expression {


                    params.ACTION == 'PLAN' ||
                    params.ACTION == 'APPLY'


                }

            }



            steps {


                dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {


                    sh """

                    terraform plan \
                    -var-file=${params.TFVARS_FILE} \
                    -out=tfplan


                    """

                }

            }

        }









        stage('Terraform Apply') {


            when {


                expression {


                    params.ACTION == 'APPLY'


                }

            }



            steps {


                dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {


                    sh """

                    terraform apply \
                    -auto-approve \
                    tfplan


                    """

                }

            }

        }









        stage('Terraform Destroy') {


            when {


                expression {


                    params.ACTION == 'DESTROY'


                }

            }



            steps {


                dir('terraform-ec2-jenkins/terraform-ec2-jenkins') {


                    sh """

                    terraform destroy \
                    -auto-approve \
                    -var-file=${params.TFVARS_FILE}


                    """

                }

            }

        }


    }



    post {


        always {

            echo "Terraform Pipeline Completed"

        }


        success {

            echo "Terraform Deployment Successful"

        }


        failure {

            echo "Terraform Deployment Failed"

        }

    }

}
